# Generated by Django 5.1 on 2024-08-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('option_type', models.CharField(choices=[('C', 'Call'), ('P', 'Put')], max_length=1)),
                ('expiration_date', models.DateField()),
                ('strike', models.PositiveIntegerField()),
                ('bid', models.PositiveIntegerField()),
                ('ask', models.PositiveIntegerField()),
            ],
        ),
    ]
